export const CHANGE_VALUE = "SEARCH/CHANGE_VALUE";

export const SEARCH_PROFILE = "SEARCH/SEARCH_PROFILE";
export const CLEAR_PROFILE = "SEARCH/CLEAR_PROFILE";

export const SHOW_LOADER = "SEARCH/SHOW_LOADER";
export const HIDE_LOADER = "SEARCH/HIDE_LOADER";

export const SHOW_ERROR = "SEARCH/SHOW_ERROR";
export const HIDE_ERROR = "SEARCH/HIDE_ERROR";
